# Generated by Django 5.0.2 on 2024-05-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='Type',
            field=models.TextField(default='message', null=True),
        ),
    ]
