# Generated by Django 5.0.2 on 2024-04-14 11:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_reportedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
