# Generated by Django 5.0.2 on 2024-03-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='OTP',
            field=models.IntegerField(null=True),
        ),
    ]
