# Generated by Django 5.0.2 on 2024-03-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_useraccount_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='display_pic',
            field=models.ImageField(blank=True, null=True, upload_to='user/'),
        ),
    ]
