# Generated by Django 5.0.2 on 2024-04-18 09:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_useraccount_display_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
